load "config/recipes/base"
load "config/recipes/nginx"
load "config/recipes/unicorn"
load "config/recipes/postgresql"
load "config/recipes/postgresql_backup"
load "config/recipes/rbenv"
load "config/recipes/check"
load "config/recipes/config_files"
load "config/recipes/assets"
load "config/recipes/newrelic"
load "config/recipes/log"
load "config/recipes/apt"
load "config/recipes/sitemap"
load "config/recipes/redis"

